# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/vision/Ball.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import Vector_pb2 as Vector__pb2
from message import Geometry_pb2 as message_dot_Geometry__pb2
import Matrix_pb2 as Matrix__pb2
import Neutron_pb2 as Neutron__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/vision/Ball.proto',
  package='message.vision',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19message/vision/Ball.proto\x12\x0emessage.vision\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cVector.proto\x1a\x16message/Geometry.proto\x1a\x0cMatrix.proto\x1a\rNeutron.proto\"\xe9\x02\n\x04\x42\x61ll\x12\x1b\n\x04\x63one\x18\x01 \x01(\x0b\x32\r.message.Cone\x12\x36\n\x0cmeasurements\x18\x02 \x03(\x0b\x32 .message.vision.Ball.Measurement\x12\x1e\n\x0escreen_angular\x18\x03 \x01(\x0b\x32\x06.fvec2\x12\x1c\n\x0c\x61ngular_size\x18\x04 \x01(\x0b\x32\x06.fvec2\x12\x16\n\x06\x63olour\x18\x05 \x01(\x0b\x32\x06.fvec4\x1as\n\x0bMeasurement\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.message.vision.Ball.MeasurementType\x12\x14\n\x04rBCc\x18\x02 \x01(\x0b\x32\x06.fvec3\x12\x1a\n\ncovariance\x18\x03 \x01(\x0b\x32\x06.fmat3\"A\n\x0fMeasurementType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0cREPROJECTION\x10\x01\x12\x0f\n\x0bWIDTH_BASED\x10\x02\"\x82\x01\n\x05\x42\x61lls\x12\x11\n\tcamera_id\x18\x01 \x01(\r\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\x03Hcw\x18\x03 \x01(\x0b\x32\x05.mat4\x12#\n\x05\x62\x61lls\x18\x04 \x03(\x0b\x32\x14.message.vision.Ballb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,Vector__pb2.DESCRIPTOR,message_dot_Geometry__pb2.DESCRIPTOR,Matrix__pb2.DESCRIPTOR,Neutron__pb2.DESCRIPTOR,])



_BALL_MEASUREMENTTYPE = _descriptor.EnumDescriptor(
  name='MeasurementType',
  full_name='message.vision.Ball.MeasurementType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPROJECTION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WIDTH_BASED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=442,
  serialized_end=507,
)
_sym_db.RegisterEnumDescriptor(_BALL_MEASUREMENTTYPE)


_BALL_MEASUREMENT = _descriptor.Descriptor(
  name='Measurement',
  full_name='message.vision.Ball.Measurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='message.vision.Ball.Measurement.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rBCc', full_name='message.vision.Ball.Measurement.rBCc', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='message.vision.Ball.Measurement.covariance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=440,
)

_BALL = _descriptor.Descriptor(
  name='Ball',
  full_name='message.vision.Ball',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cone', full_name='message.vision.Ball.cone', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurements', full_name='message.vision.Ball.measurements', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='screen_angular', full_name='message.vision.Ball.screen_angular', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_size', full_name='message.vision.Ball.angular_size', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colour', full_name='message.vision.Ball.colour', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BALL_MEASUREMENT, ],
  enum_types=[
    _BALL_MEASUREMENTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=507,
)


_BALLS = _descriptor.Descriptor(
  name='Balls',
  full_name='message.vision.Balls',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='message.vision.Balls.camera_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.vision.Balls.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Hcw', full_name='message.vision.Balls.Hcw', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balls', full_name='message.vision.Balls.balls', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=640,
)

_BALL_MEASUREMENT.fields_by_name['type'].enum_type = _BALL_MEASUREMENTTYPE
_BALL_MEASUREMENT.fields_by_name['rBCc'].message_type = Vector__pb2._FVEC3
_BALL_MEASUREMENT.fields_by_name['covariance'].message_type = Matrix__pb2._FMAT3
_BALL_MEASUREMENT.containing_type = _BALL
_BALL.fields_by_name['cone'].message_type = message_dot_Geometry__pb2._CONE
_BALL.fields_by_name['measurements'].message_type = _BALL_MEASUREMENT
_BALL.fields_by_name['screen_angular'].message_type = Vector__pb2._FVEC2
_BALL.fields_by_name['angular_size'].message_type = Vector__pb2._FVEC2
_BALL.fields_by_name['colour'].message_type = Vector__pb2._FVEC4
_BALL_MEASUREMENTTYPE.containing_type = _BALL
_BALLS.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_BALLS.fields_by_name['Hcw'].message_type = Matrix__pb2._MAT4
_BALLS.fields_by_name['balls'].message_type = _BALL
DESCRIPTOR.message_types_by_name['Ball'] = _BALL
DESCRIPTOR.message_types_by_name['Balls'] = _BALLS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ball = _reflection.GeneratedProtocolMessageType('Ball', (_message.Message,), dict(

  Measurement = _reflection.GeneratedProtocolMessageType('Measurement', (_message.Message,), dict(
    DESCRIPTOR = _BALL_MEASUREMENT,
    __module__ = 'message.vision.Ball_pb2'
    # @@protoc_insertion_point(class_scope:message.vision.Ball.Measurement)
    ))
  ,
  DESCRIPTOR = _BALL,
  __module__ = 'message.vision.Ball_pb2'
  # @@protoc_insertion_point(class_scope:message.vision.Ball)
  ))
_sym_db.RegisterMessage(Ball)
_sym_db.RegisterMessage(Ball.Measurement)

Balls = _reflection.GeneratedProtocolMessageType('Balls', (_message.Message,), dict(
  DESCRIPTOR = _BALLS,
  __module__ = 'message.vision.Ball_pb2'
  # @@protoc_insertion_point(class_scope:message.vision.Balls)
  ))
_sym_db.RegisterMessage(Balls)


# @@protoc_insertion_point(module_scope)
