# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/vision/GreenHorizon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import Neutron_pb2 as Neutron__pb2
import Matrix_pb2 as Matrix__pb2
import Vector_pb2 as Vector__pb2
from message.vision import VisualMesh_pb2 as message_dot_vision_dot_VisualMesh__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/vision/GreenHorizon.proto',
  package='message.vision',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!message/vision/GreenHorizon.proto\x12\x0emessage.vision\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rNeutron.proto\x1a\x0cMatrix.proto\x1a\x0cVector.proto\x1a\x1fmessage/vision/VisualMesh.proto\"\xad\x01\n\x0cGreenHorizon\x12\x17\n\x07horizon\x18\x01 \x03(\x0b\x32\x06.fvec3\x12\x12\n\x03Hcw\x18\x02 \x01(\x0b\x32\x05.mat4\x12\x11\n\tcamera_id\x18\x03 \x01(\r\x12.\n\x04mesh\x18\x04 \x01(\x0b\x32\x1a.message.vision.VisualMeshB\x04\x80\xb5\x18\x02\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,Neutron__pb2.DESCRIPTOR,Matrix__pb2.DESCRIPTOR,Vector__pb2.DESCRIPTOR,message_dot_vision_dot_VisualMesh__pb2.DESCRIPTOR,])




_GREENHORIZON = _descriptor.Descriptor(
  name='GreenHorizon',
  full_name='message.vision.GreenHorizon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='horizon', full_name='message.vision.GreenHorizon.horizon', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Hcw', full_name='message.vision.GreenHorizon.Hcw', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='message.vision.GreenHorizon.camera_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mesh', full_name='message.vision.GreenHorizon.mesh', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\200\265\030\002'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.vision.GreenHorizon.timestamp', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=336,
)

_GREENHORIZON.fields_by_name['horizon'].message_type = Vector__pb2._FVEC3
_GREENHORIZON.fields_by_name['Hcw'].message_type = Matrix__pb2._MAT4
_GREENHORIZON.fields_by_name['mesh'].message_type = message_dot_vision_dot_VisualMesh__pb2._VISUALMESH
_GREENHORIZON.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['GreenHorizon'] = _GREENHORIZON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GreenHorizon = _reflection.GeneratedProtocolMessageType('GreenHorizon', (_message.Message,), dict(
  DESCRIPTOR = _GREENHORIZON,
  __module__ = 'message.vision.GreenHorizon_pb2'
  # @@protoc_insertion_point(class_scope:message.vision.GreenHorizon)
  ))
_sym_db.RegisterMessage(GreenHorizon)


_GREENHORIZON.fields_by_name['mesh']._options = None
# @@protoc_insertion_point(module_scope)
