# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/vision/Line.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/vision/Line.proto',
  package='message.vision',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19message/vision/Line.proto\x12\x0emessage.vision\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cVector.proto\"\x8b\x01\n\x04Line\x12\x11\n\tcamera_id\x18\x01 \x01(\r\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\x05start\x18\x03 \x01(\x0b\x32\x06.ivec2\x12\x13\n\x03\x65nd\x18\x04 \x01(\x0b\x32\x06.ivec2\x12\x15\n\x06\x63olour\x18\x05 \x01(\x0b\x32\x05.vec4\",\n\x05Lines\x12#\n\x05lines\x18\x01 \x03(\x0b\x32\x14.message.vision.Lineb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,Vector__pb2.DESCRIPTOR,])




_LINE = _descriptor.Descriptor(
  name='Line',
  full_name='message.vision.Line',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='message.vision.Line.camera_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.vision.Line.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='message.vision.Line.start', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='message.vision.Line.end', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colour', full_name='message.vision.Line.colour', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=232,
)


_LINES = _descriptor.Descriptor(
  name='Lines',
  full_name='message.vision.Lines',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lines', full_name='message.vision.Lines.lines', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=278,
)

_LINE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LINE.fields_by_name['start'].message_type = Vector__pb2._IVEC2
_LINE.fields_by_name['end'].message_type = Vector__pb2._IVEC2
_LINE.fields_by_name['colour'].message_type = Vector__pb2._VEC4
_LINES.fields_by_name['lines'].message_type = _LINE
DESCRIPTOR.message_types_by_name['Line'] = _LINE
DESCRIPTOR.message_types_by_name['Lines'] = _LINES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Line = _reflection.GeneratedProtocolMessageType('Line', (_message.Message,), dict(
  DESCRIPTOR = _LINE,
  __module__ = 'message.vision.Line_pb2'
  # @@protoc_insertion_point(class_scope:message.vision.Line)
  ))
_sym_db.RegisterMessage(Line)

Lines = _reflection.GeneratedProtocolMessageType('Lines', (_message.Message,), dict(
  DESCRIPTOR = _LINES,
  __module__ = 'message.vision.Line_pb2'
  # @@protoc_insertion_point(class_scope:message.vision.Lines)
  ))
_sym_db.RegisterMessage(Lines)


# @@protoc_insertion_point(module_scope)
