# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/vision/Obstacle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from message import Geometry_pb2 as message_dot_Geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/vision/Obstacle.proto',
  package='message.vision',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dmessage/vision/Obstacle.proto\x12\x0emessage.vision\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16message/Geometry.proto\"\xcb\x01\n\x08Obstacle\x12\x11\n\tcamera_id\x18\x01 \x01(\r\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1f\n\x05shape\x18\x03 \x01(\x0b\x32\x10.message.Polygon\x12+\n\x04team\x18\x04 \x01(\x0e\x32\x1d.message.vision.Obstacle.Team\"/\n\x04Team\x12\x10\n\x0cUNKNOWN_TEAM\x10\x00\x12\x0b\n\x07MAGENTA\x10\x01\x12\x08\n\x04\x43YAN\x10\x02\"4\n\tObstacles\x12\'\n\x05lines\x18\x01 \x03(\x0b\x32\x18.message.vision.Obstacleb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,message_dot_Geometry__pb2.DESCRIPTOR,])



_OBSTACLE_TEAM = _descriptor.EnumDescriptor(
  name='Team',
  full_name='message.vision.Obstacle.Team',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TEAM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAGENTA', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CYAN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=263,
  serialized_end=310,
)
_sym_db.RegisterEnumDescriptor(_OBSTACLE_TEAM)


_OBSTACLE = _descriptor.Descriptor(
  name='Obstacle',
  full_name='message.vision.Obstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='message.vision.Obstacle.camera_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.vision.Obstacle.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='message.vision.Obstacle.shape', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team', full_name='message.vision.Obstacle.team', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OBSTACLE_TEAM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=310,
)


_OBSTACLES = _descriptor.Descriptor(
  name='Obstacles',
  full_name='message.vision.Obstacles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lines', full_name='message.vision.Obstacles.lines', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=364,
)

_OBSTACLE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OBSTACLE.fields_by_name['shape'].message_type = message_dot_Geometry__pb2._POLYGON
_OBSTACLE.fields_by_name['team'].enum_type = _OBSTACLE_TEAM
_OBSTACLE_TEAM.containing_type = _OBSTACLE
_OBSTACLES.fields_by_name['lines'].message_type = _OBSTACLE
DESCRIPTOR.message_types_by_name['Obstacle'] = _OBSTACLE
DESCRIPTOR.message_types_by_name['Obstacles'] = _OBSTACLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Obstacle = _reflection.GeneratedProtocolMessageType('Obstacle', (_message.Message,), dict(
  DESCRIPTOR = _OBSTACLE,
  __module__ = 'message.vision.Obstacle_pb2'
  # @@protoc_insertion_point(class_scope:message.vision.Obstacle)
  ))
_sym_db.RegisterMessage(Obstacle)

Obstacles = _reflection.GeneratedProtocolMessageType('Obstacles', (_message.Message,), dict(
  DESCRIPTOR = _OBSTACLES,
  __module__ = 'message.vision.Obstacle_pb2'
  # @@protoc_insertion_point(class_scope:message.vision.Obstacles)
  ))
_sym_db.RegisterMessage(Obstacles)


# @@protoc_insertion_point(module_scope)
