# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/vision/VisualMesh.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import Neutron_pb2 as Neutron__pb2
import Matrix_pb2 as Matrix__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/vision/VisualMesh.proto',
  package='message.vision',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fmessage/vision/VisualMesh.proto\x12\x0emessage.vision\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rNeutron.proto\x1a\x0cMatrix.proto\"\xba\x02\n\nVisualMesh\x12\x11\n\tcamera_id\x18\x01 \x01(\r\x12\x13\n\x04rays\x18\x02 \x01(\x0b\x32\x05.fmat\x12\x1c\n\rneighbourhood\x18\x03 \x01(\x0b\x32\x05.imat\x12\x1e\n\x0f\x63lassifications\x18\x04 \x01(\x0b\x32\x05.fmat\x12\x1a\n\x0b\x63oordinates\x18\x05 \x01(\x0b\x32\x05.fmat\x12\x13\n\x07indices\x18\x06 \x03(\x05\x42\x02\x10\x01\x12\x12\n\x03Hcw\x18\x07 \x01(\x0b\x32\x05.mat4\x12,\n\x04mesh\x18\x08 \x03(\x0b\x32\x1e.message.vision.VisualMesh.Row\x12-\n\ttimestamp\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a$\n\x03Row\x12\x0b\n\x03phi\x18\x01 \x01(\x02\x12\x10\n\x08segments\x18\x02 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,Neutron__pb2.DESCRIPTOR,Matrix__pb2.DESCRIPTOR,])




_VISUALMESH_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='message.vision.VisualMesh.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phi', full_name='message.vision.VisualMesh.Row.phi', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segments', full_name='message.vision.VisualMesh.Row.segments', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=428,
)

_VISUALMESH = _descriptor.Descriptor(
  name='VisualMesh',
  full_name='message.vision.VisualMesh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='message.vision.VisualMesh.camera_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rays', full_name='message.vision.VisualMesh.rays', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neighbourhood', full_name='message.vision.VisualMesh.neighbourhood', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classifications', full_name='message.vision.VisualMesh.classifications', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='message.vision.VisualMesh.coordinates', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indices', full_name='message.vision.VisualMesh.indices', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Hcw', full_name='message.vision.VisualMesh.Hcw', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mesh', full_name='message.vision.VisualMesh.mesh', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.vision.VisualMesh.timestamp', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VISUALMESH_ROW, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=428,
)

_VISUALMESH_ROW.containing_type = _VISUALMESH
_VISUALMESH.fields_by_name['rays'].message_type = Matrix__pb2._FMAT
_VISUALMESH.fields_by_name['neighbourhood'].message_type = Matrix__pb2._IMAT
_VISUALMESH.fields_by_name['classifications'].message_type = Matrix__pb2._FMAT
_VISUALMESH.fields_by_name['coordinates'].message_type = Matrix__pb2._FMAT
_VISUALMESH.fields_by_name['Hcw'].message_type = Matrix__pb2._MAT4
_VISUALMESH.fields_by_name['mesh'].message_type = _VISUALMESH_ROW
_VISUALMESH.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['VisualMesh'] = _VISUALMESH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisualMesh = _reflection.GeneratedProtocolMessageType('VisualMesh', (_message.Message,), dict(

  Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
    DESCRIPTOR = _VISUALMESH_ROW,
    __module__ = 'message.vision.VisualMesh_pb2'
    # @@protoc_insertion_point(class_scope:message.vision.VisualMesh.Row)
    ))
  ,
  DESCRIPTOR = _VISUALMESH,
  __module__ = 'message.vision.VisualMesh_pb2'
  # @@protoc_insertion_point(class_scope:message.vision.VisualMesh)
  ))
_sym_db.RegisterMessage(VisualMesh)
_sym_db.RegisterMessage(VisualMesh.Row)


_VISUALMESH.fields_by_name['indices']._options = None
# @@protoc_insertion_point(module_scope)
