# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/behaviour/MotionCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/behaviour/MotionCommand.proto',
  package='message.behaviour',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%message/behaviour/MotionCommand.proto\x12\x11message.behaviour\x1a\x0cVector.proto\"\xe3\x01\n\rMotionCommand\x12\x33\n\x04type\x18\x01 \x01(\x0e\x32%.message.behaviour.MotionCommand.Type\x12\x18\n\tgoalState\x18\x02 \x01(\x0b\x32\x05.vec3\x12\x19\n\nkickTarget\x18\x03 \x01(\x0b\x32\x05.vec2\x12\x1a\n\x0bwalkCommand\x18\x04 \x01(\x0b\x32\x05.vec3\"L\n\x04Type\x12\x0e\n\nStandStill\x10\x00\x12\x0f\n\x0bWalkToState\x10\x01\x12\x10\n\x0c\x42\x61llApproach\x10\x02\x12\x11\n\rDirectCommand\x10\x03\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])



_MOTIONCOMMAND_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='message.behaviour.MotionCommand.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='StandStill', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WalkToState', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BallApproach', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DirectCommand', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=226,
  serialized_end=302,
)
_sym_db.RegisterEnumDescriptor(_MOTIONCOMMAND_TYPE)


_MOTIONCOMMAND = _descriptor.Descriptor(
  name='MotionCommand',
  full_name='message.behaviour.MotionCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='message.behaviour.MotionCommand.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goalState', full_name='message.behaviour.MotionCommand.goalState', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kickTarget', full_name='message.behaviour.MotionCommand.kickTarget', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='walkCommand', full_name='message.behaviour.MotionCommand.walkCommand', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MOTIONCOMMAND_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=302,
)

_MOTIONCOMMAND.fields_by_name['type'].enum_type = _MOTIONCOMMAND_TYPE
_MOTIONCOMMAND.fields_by_name['goalState'].message_type = Vector__pb2._VEC3
_MOTIONCOMMAND.fields_by_name['kickTarget'].message_type = Vector__pb2._VEC2
_MOTIONCOMMAND.fields_by_name['walkCommand'].message_type = Vector__pb2._VEC3
_MOTIONCOMMAND_TYPE.containing_type = _MOTIONCOMMAND
DESCRIPTOR.message_types_by_name['MotionCommand'] = _MOTIONCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotionCommand = _reflection.GeneratedProtocolMessageType('MotionCommand', (_message.Message,), dict(
  DESCRIPTOR = _MOTIONCOMMAND,
  __module__ = 'message.behaviour.MotionCommand_pb2'
  # @@protoc_insertion_point(class_scope:message.behaviour.MotionCommand)
  ))
_sym_db.RegisterMessage(MotionCommand)


# @@protoc_insertion_point(module_scope)
