# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/behaviour/ServoCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/behaviour/ServoCommand.proto',
  package='message.behaviour',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$message/behaviour/ServoCommand.proto\x12\x11message.behaviour\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n\x0cServoCommand\x12\x0e\n\x06source\x18\x01 \x01(\x04\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\n\n\x02id\x18\x03 \x01(\r\x12\x10\n\x08position\x18\x04 \x01(\x02\x12\x0c\n\x04gain\x18\x05 \x01(\x02\x12\x0e\n\x06torque\x18\x06 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SERVOCOMMAND = _descriptor.Descriptor(
  name='ServoCommand',
  full_name='message.behaviour.ServoCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='message.behaviour.ServoCommand.source', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='message.behaviour.ServoCommand.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='message.behaviour.ServoCommand.id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='message.behaviour.ServoCommand.position', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain', full_name='message.behaviour.ServoCommand.gain', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque', full_name='message.behaviour.ServoCommand.torque', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=225,
)

_SERVOCOMMAND.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ServoCommand'] = _SERVOCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServoCommand = _reflection.GeneratedProtocolMessageType('ServoCommand', (_message.Message,), dict(
  DESCRIPTOR = _SERVOCOMMAND,
  __module__ = 'message.behaviour.ServoCommand_pb2'
  # @@protoc_insertion_point(class_scope:message.behaviour.ServoCommand)
  ))
_sym_db.RegisterMessage(ServoCommand)


# @@protoc_insertion_point(module_scope)
