# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/behaviour/SoccerObjectPriority.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/behaviour/SoccerObjectPriority.proto',
  package='message.behaviour',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,message/behaviour/SoccerObjectPriority.proto\x12\x11message.behaviour\"\x9b\x02\n\x14SoccerObjectPriority\x12\x0c\n\x04\x62\x61ll\x18\x01 \x01(\x05\x12\x0c\n\x04goal\x18\x02 \x01(\x05\x12\x0c\n\x04line\x18\x03 \x01(\x05\x12\x46\n\nsearchType\x18\x04 \x01(\x0e\x32\x32.message.behaviour.SoccerObjectPriority.SearchType\"\x90\x01\n\nSearchType\x12\x08\n\x04LOST\x10\x00\x12\x1b\n\x17\x46IND_ADDITIONAL_OBJECTS\x10\x01\x12\x0f\n\x0bGOAL_SEARCH\x10\x02\x12\r\n\tGOAL_LEFT\x10\x03\x12\x0e\n\nGOAL_RIGHT\x10\x04\x12\x0f\n\x0bGROUND_LEFT\x10\x05\x12\x10\n\x0cGROUND_RIGHT\x10\x06\x12\x08\n\x04OTHE\x10\x07\x62\x06proto3')
)



_SOCCEROBJECTPRIORITY_SEARCHTYPE = _descriptor.EnumDescriptor(
  name='SearchType',
  full_name='message.behaviour.SoccerObjectPriority.SearchType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOST', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIND_ADDITIONAL_OBJECTS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOAL_SEARCH', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOAL_LEFT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOAL_RIGHT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUND_LEFT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUND_RIGHT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHE', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=207,
  serialized_end=351,
)
_sym_db.RegisterEnumDescriptor(_SOCCEROBJECTPRIORITY_SEARCHTYPE)


_SOCCEROBJECTPRIORITY = _descriptor.Descriptor(
  name='SoccerObjectPriority',
  full_name='message.behaviour.SoccerObjectPriority',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ball', full_name='message.behaviour.SoccerObjectPriority.ball', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goal', full_name='message.behaviour.SoccerObjectPriority.goal', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line', full_name='message.behaviour.SoccerObjectPriority.line', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='searchType', full_name='message.behaviour.SoccerObjectPriority.searchType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SOCCEROBJECTPRIORITY_SEARCHTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=351,
)

_SOCCEROBJECTPRIORITY.fields_by_name['searchType'].enum_type = _SOCCEROBJECTPRIORITY_SEARCHTYPE
_SOCCEROBJECTPRIORITY_SEARCHTYPE.containing_type = _SOCCEROBJECTPRIORITY
DESCRIPTOR.message_types_by_name['SoccerObjectPriority'] = _SOCCEROBJECTPRIORITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SoccerObjectPriority = _reflection.GeneratedProtocolMessageType('SoccerObjectPriority', (_message.Message,), dict(
  DESCRIPTOR = _SOCCEROBJECTPRIORITY,
  __module__ = 'message.behaviour.SoccerObjectPriority_pb2'
  # @@protoc_insertion_point(class_scope:message.behaviour.SoccerObjectPriority)
  ))
_sym_db.RegisterMessage(SoccerObjectPriority)


# @@protoc_insertion_point(module_scope)
