# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/behaviour/Subsumption.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/behaviour/Subsumption.proto',
  package='message.behaviour',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#message/behaviour/Subsumption.proto\x12\x11message.behaviour\"\xde\x04\n\x0bSubsumption\x12\x46\n\x0f\x61\x63tion_register\x18\x01 \x03(\x0b\x32-.message.behaviour.Subsumption.ActionRegister\x12M\n\x13\x61\x63tion_state_change\x18\x02 \x03(\x0b\x32\x30.message.behaviour.Subsumption.ActionStateChange\x12N\n\x16\x61\x63tion_priority_change\x18\x03 \x03(\x0b\x32..message.behaviour.Subsumption.ActionPriorites\x1a*\n\x07LimbSet\x12\x10\n\x08priority\x18\x01 \x01(\x02\x12\r\n\x05limbs\x18\x02 \x03(\r\x1a\x64\n\x0e\x41\x63tionRegister\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x38\n\x08limb_set\x18\x03 \x03(\x0b\x32&.message.behaviour.Subsumption.LimbSet\x1a\xa2\x01\n\x11\x41\x63tionStateChange\x12\x45\n\x05state\x18\x01 \x01(\x0e\x32\x36.message.behaviour.Subsumption.ActionStateChange.State\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05limbs\x18\x03 \x03(\r\")\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05START\x10\x01\x12\x08\n\x04KILL\x10\x02\x1a\x31\n\x0f\x41\x63tionPriorites\x12\n\n\x02id\x18\x01 \x01(\r\x12\x12\n\npriorities\x18\x02 \x03(\x02\x62\x06proto3')
)



_SUBSUMPTION_ACTIONSTATECHANGE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='message.behaviour.Subsumption.ActionStateChange.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KILL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=573,
  serialized_end=614,
)
_sym_db.RegisterEnumDescriptor(_SUBSUMPTION_ACTIONSTATECHANGE_STATE)


_SUBSUMPTION_LIMBSET = _descriptor.Descriptor(
  name='LimbSet',
  full_name='message.behaviour.Subsumption.LimbSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='message.behaviour.Subsumption.LimbSet.priority', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limbs', full_name='message.behaviour.Subsumption.LimbSet.limbs', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=347,
)

_SUBSUMPTION_ACTIONREGISTER = _descriptor.Descriptor(
  name='ActionRegister',
  full_name='message.behaviour.Subsumption.ActionRegister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='message.behaviour.Subsumption.ActionRegister.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='message.behaviour.Subsumption.ActionRegister.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limb_set', full_name='message.behaviour.Subsumption.ActionRegister.limb_set', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=449,
)

_SUBSUMPTION_ACTIONSTATECHANGE = _descriptor.Descriptor(
  name='ActionStateChange',
  full_name='message.behaviour.Subsumption.ActionStateChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='message.behaviour.Subsumption.ActionStateChange.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='message.behaviour.Subsumption.ActionStateChange.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limbs', full_name='message.behaviour.Subsumption.ActionStateChange.limbs', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SUBSUMPTION_ACTIONSTATECHANGE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=614,
)

_SUBSUMPTION_ACTIONPRIORITES = _descriptor.Descriptor(
  name='ActionPriorites',
  full_name='message.behaviour.Subsumption.ActionPriorites',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='message.behaviour.Subsumption.ActionPriorites.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priorities', full_name='message.behaviour.Subsumption.ActionPriorites.priorities', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=665,
)

_SUBSUMPTION = _descriptor.Descriptor(
  name='Subsumption',
  full_name='message.behaviour.Subsumption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_register', full_name='message.behaviour.Subsumption.action_register', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_state_change', full_name='message.behaviour.Subsumption.action_state_change', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_priority_change', full_name='message.behaviour.Subsumption.action_priority_change', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SUBSUMPTION_LIMBSET, _SUBSUMPTION_ACTIONREGISTER, _SUBSUMPTION_ACTIONSTATECHANGE, _SUBSUMPTION_ACTIONPRIORITES, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=665,
)

_SUBSUMPTION_LIMBSET.containing_type = _SUBSUMPTION
_SUBSUMPTION_ACTIONREGISTER.fields_by_name['limb_set'].message_type = _SUBSUMPTION_LIMBSET
_SUBSUMPTION_ACTIONREGISTER.containing_type = _SUBSUMPTION
_SUBSUMPTION_ACTIONSTATECHANGE.fields_by_name['state'].enum_type = _SUBSUMPTION_ACTIONSTATECHANGE_STATE
_SUBSUMPTION_ACTIONSTATECHANGE.containing_type = _SUBSUMPTION
_SUBSUMPTION_ACTIONSTATECHANGE_STATE.containing_type = _SUBSUMPTION_ACTIONSTATECHANGE
_SUBSUMPTION_ACTIONPRIORITES.containing_type = _SUBSUMPTION
_SUBSUMPTION.fields_by_name['action_register'].message_type = _SUBSUMPTION_ACTIONREGISTER
_SUBSUMPTION.fields_by_name['action_state_change'].message_type = _SUBSUMPTION_ACTIONSTATECHANGE
_SUBSUMPTION.fields_by_name['action_priority_change'].message_type = _SUBSUMPTION_ACTIONPRIORITES
DESCRIPTOR.message_types_by_name['Subsumption'] = _SUBSUMPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Subsumption = _reflection.GeneratedProtocolMessageType('Subsumption', (_message.Message,), dict(

  LimbSet = _reflection.GeneratedProtocolMessageType('LimbSet', (_message.Message,), dict(
    DESCRIPTOR = _SUBSUMPTION_LIMBSET,
    __module__ = 'message.behaviour.Subsumption_pb2'
    # @@protoc_insertion_point(class_scope:message.behaviour.Subsumption.LimbSet)
    ))
  ,

  ActionRegister = _reflection.GeneratedProtocolMessageType('ActionRegister', (_message.Message,), dict(
    DESCRIPTOR = _SUBSUMPTION_ACTIONREGISTER,
    __module__ = 'message.behaviour.Subsumption_pb2'
    # @@protoc_insertion_point(class_scope:message.behaviour.Subsumption.ActionRegister)
    ))
  ,

  ActionStateChange = _reflection.GeneratedProtocolMessageType('ActionStateChange', (_message.Message,), dict(
    DESCRIPTOR = _SUBSUMPTION_ACTIONSTATECHANGE,
    __module__ = 'message.behaviour.Subsumption_pb2'
    # @@protoc_insertion_point(class_scope:message.behaviour.Subsumption.ActionStateChange)
    ))
  ,

  ActionPriorites = _reflection.GeneratedProtocolMessageType('ActionPriorites', (_message.Message,), dict(
    DESCRIPTOR = _SUBSUMPTION_ACTIONPRIORITES,
    __module__ = 'message.behaviour.Subsumption_pb2'
    # @@protoc_insertion_point(class_scope:message.behaviour.Subsumption.ActionPriorites)
    ))
  ,
  DESCRIPTOR = _SUBSUMPTION,
  __module__ = 'message.behaviour.Subsumption_pb2'
  # @@protoc_insertion_point(class_scope:message.behaviour.Subsumption)
  ))
_sym_db.RegisterMessage(Subsumption)
_sym_db.RegisterMessage(Subsumption.LimbSet)
_sym_db.RegisterMessage(Subsumption.ActionRegister)
_sym_db.RegisterMessage(Subsumption.ActionStateChange)
_sym_db.RegisterMessage(Subsumption.ActionPriorites)


# @@protoc_insertion_point(module_scope)
