# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Neutron.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Neutron.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rNeutron.proto\x1a google/protobuf/descriptor.proto*8\n\x0bPointerType\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03RAW\x10\x01\x12\n\n\x06SHARED\x10\x02\x12\n\n\x06UNIQUE\x10\x03:>\n\x07pointer\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\x0e\x32\x0c.PointerType:3\n\narray_size\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\rb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])

_POINTERTYPE = _descriptor.EnumDescriptor(
  name='PointerType',
  full_name='PointerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHARED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIQUE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=51,
  serialized_end=107,
)
_sym_db.RegisterEnumDescriptor(_POINTERTYPE)

PointerType = enum_type_wrapper.EnumTypeWrapper(_POINTERTYPE)
NONE = 0
RAW = 1
SHARED = 2
UNIQUE = 3

POINTER_FIELD_NUMBER = 50000
pointer = _descriptor.FieldDescriptor(
  name='pointer', full_name='pointer', index=0,
  number=50000, type=14, cpp_type=8, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
ARRAY_SIZE_FIELD_NUMBER = 50001
array_size = _descriptor.FieldDescriptor(
  name='array_size', full_name='array_size', index=1,
  number=50001, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

DESCRIPTOR.enum_types_by_name['PointerType'] = _POINTERTYPE
DESCRIPTOR.extensions_by_name['pointer'] = pointer
DESCRIPTOR.extensions_by_name['array_size'] = array_size
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

pointer.enum_type = _POINTERTYPE
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(pointer)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(array_size)

# @@protoc_insertion_point(module_scope)
