steps:
  # Push up new images to DockerHub when they get to master
  # Makes development faster as you can just pull the images rather than building them yourself
  # If you make modifications to the Dockerfile it should resume from the common point in master
  - label: ":docker: Push new images"
    branches: master
    agents:
      dockerhub: true
    plugins:
      - docker-login#v2.0.1:
          username: nubotsdocker
          # Dockerhub password is loaded from the environment hook via DOCKER_LOGIN_PASSWORD environment variable
      - docker-compose#v3.1.0:
          config: .buildkite/docker-compose.yml
          push:
            - generic:nubots/nubots:generic
            - nuc7i7bnh:nubots/nubots:nuc7i7bnh
  # Build for the NUC
  - label: "Build for NUC"
    command: "./b configure -- -DBUILD_TESTS=ON && ./b build && ./b build test"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          pull: nuc7i7bnh_image
          run: nuc7i7bnh
          workdir: /home/nubots/NUbots/

  # Formatting
  - label: "Validate C++ and Protobuf formatting"
    command: ".buildkite/scripts/validate_clang_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          pull: generic_image
          run: generic
          workdir: /home/nubots/NUbots/
  - label: "Validate CMake formatting"
    command: ".buildkite/scripts/validate_cmake_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          pull: generic_image
          run: generic
          workdir: /home/nubots/NUbots/
  - label: "Validate Python formatting"
    command: ".buildkite/scripts/validate_python_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          pull: generic_image
          run: generic
          workdir: /home/nubots/NUbots/
