steps:
  - label: ":docker: Install toolchain and supporting packages"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    plugins:
      docker-compose#v2.5.0:
        build: nubots
        workdir: .
        config:
          - docker-compose.yml


  - wait

  - label: ":scroll: Validate code format"
    command: ".buildkite/validate_format.sh"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    plugins:
      docker-compose#v2.5.0:
        run: nubots
        workdir: .
        config:
          - docker-compose.yml

  - wait

  - label: ":hammer: Build code"
    command: ".buildkite/install.sh"
    artifact_paths: "build_native/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    plugins:
      docker-compose#v2.5.0:
        run: nubots
        workdir: .
        config:
          - docker-compose.yml
        env:
          PATH: "/usr/lib/ccache:$$PATH"
