steps:
  # Build for the NUC
  - label: "Build for NUC"
    command: "/code/NUbots/.buildkite/scripts/build_code.sh"
    plugins:
      - docker#v3.3.0:
          image: "nubots/buildkite:0.4"
          workdir: "/code/NUbots"
          propagate-uid-gid: true
          environment:
            - "PLATFORM=nuc7i7bnh"

  # Validate formatting
  - label: "Validate C++ and Protobuf formatting"
    command: "/code/NUbots/.buildkite/scripts/validate_clang_format.sh"
    plugins:
      - docker#v3.3.0:
          image: "nubots/buildkite:0.4"
          workdir: "/code/NUbots"
          propagate-uid-gid: true
  - label: "Validate CMake formatting"
    command: "/code/NUbots/.buildkite/scripts/validate_cmake_format.sh"
    plugins:
      - docker#v3.3.0:
          image: "nubots/buildkite:0.4"
          workdir: "/code/NUbots"
          propagate-uid-gid: true
