steps:
  # Build for the NUC
  - label: "Build for NUC"
    command: "./b build"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: nuc7i7bnh
          workdir: /home/nubots/NUbots/

  # Formatting
  - label: "Validate C++ and Protobuf formatting"
    command: ".buildkite/scripts/validate_clang_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: generic
          workdir: /home/nubots/NUbots/
  - label: "Validate CMake formatting"
    command: ".buildkite/scripts/validate_cmake_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: generic
          workdir: /home/nubots/NUbots/
  - label: "Validate Python formatting"
    command: ".buildkite/scripts/validate_python_format.sh"
    plugins:
      - docker-compose#v3.0.3:
          config: .buildkite/docker-compose.yml
          run: generic
          workdir: /home/nubots/NUbots/
