# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/Geometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2
import Matrix_pb2 as Matrix__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/Geometry.proto',
  package='message',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16message/Geometry.proto\x12\x07message\x1a\x0cVector.proto\x1a\x0cMatrix.proto\"0\n\x04Line\x12\x16\n\x06normal\x18\x01 \x01(\x0b\x32\x06.fvec3\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\"/\n\x06\x43ircle\x12\x0e\n\x06radius\x18\x01 \x01(\x01\x12\x15\n\x06\x63\x65ntre\x18\x02 \x01(\x0b\x32\x05.vec2\"!\n\x07\x45llipse\x12\x16\n\x07\x65llipse\x18\x01 \x01(\x0b\x32\x05.mat3\"R\n\x04Quad\x12\x11\n\x02tl\x18\x01 \x01(\x0b\x32\x05.vec2\x12\x11\n\x02tr\x18\x02 \x01(\x0b\x32\x05.vec2\x12\x11\n\x02\x62l\x18\x03 \x01(\x0b\x32\x05.vec2\x12\x11\n\x02\x62r\x18\x04 \x01(\x0b\x32\x05.vec2\"\x1f\n\x07Polygon\x12\x14\n\x05point\x18\x01 \x01(\x0b\x32\x05.vec2\"U\n\x07\x46rustum\x12\x11\n\x02tl\x18\x01 \x01(\x0b\x32\x05.vec3\x12\x11\n\x02tr\x18\x02 \x01(\x0b\x32\x05.vec3\x12\x11\n\x02\x62l\x18\x03 \x01(\x0b\x32\x05.vec3\x12\x11\n\x02\x62r\x18\x04 \x01(\x0b\x32\x05.vec3\">\n\x04\x43one\x12\x14\n\x04\x61xis\x18\x01 \x01(\x0b\x32\x06.fvec3\x12\x10\n\x08gradient\x18\x02 \x01(\x02\x12\x0e\n\x06radius\x18\x03 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,Matrix__pb2.DESCRIPTOR,])




_LINE = _descriptor.Descriptor(
  name='Line',
  full_name='message.Line',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='normal', full_name='message.Line.normal', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='message.Line.distance', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=111,
)


_CIRCLE = _descriptor.Descriptor(
  name='Circle',
  full_name='message.Circle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radius', full_name='message.Circle.radius', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='centre', full_name='message.Circle.centre', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=160,
)


_ELLIPSE = _descriptor.Descriptor(
  name='Ellipse',
  full_name='message.Ellipse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ellipse', full_name='message.Ellipse.ellipse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=195,
)


_QUAD = _descriptor.Descriptor(
  name='Quad',
  full_name='message.Quad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tl', full_name='message.Quad.tl', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tr', full_name='message.Quad.tr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bl', full_name='message.Quad.bl', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='br', full_name='message.Quad.br', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=279,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='message.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='message.Polygon.point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=312,
)


_FRUSTUM = _descriptor.Descriptor(
  name='Frustum',
  full_name='message.Frustum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tl', full_name='message.Frustum.tl', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tr', full_name='message.Frustum.tr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bl', full_name='message.Frustum.bl', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='br', full_name='message.Frustum.br', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=399,
)


_CONE = _descriptor.Descriptor(
  name='Cone',
  full_name='message.Cone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='axis', full_name='message.Cone.axis', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gradient', full_name='message.Cone.gradient', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='message.Cone.radius', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=463,
)

_LINE.fields_by_name['normal'].message_type = Vector__pb2._FVEC3
_CIRCLE.fields_by_name['centre'].message_type = Vector__pb2._VEC2
_ELLIPSE.fields_by_name['ellipse'].message_type = Matrix__pb2._MAT3
_QUAD.fields_by_name['tl'].message_type = Vector__pb2._VEC2
_QUAD.fields_by_name['tr'].message_type = Vector__pb2._VEC2
_QUAD.fields_by_name['bl'].message_type = Vector__pb2._VEC2
_QUAD.fields_by_name['br'].message_type = Vector__pb2._VEC2
_POLYGON.fields_by_name['point'].message_type = Vector__pb2._VEC2
_FRUSTUM.fields_by_name['tl'].message_type = Vector__pb2._VEC3
_FRUSTUM.fields_by_name['tr'].message_type = Vector__pb2._VEC3
_FRUSTUM.fields_by_name['bl'].message_type = Vector__pb2._VEC3
_FRUSTUM.fields_by_name['br'].message_type = Vector__pb2._VEC3
_CONE.fields_by_name['axis'].message_type = Vector__pb2._FVEC3
DESCRIPTOR.message_types_by_name['Line'] = _LINE
DESCRIPTOR.message_types_by_name['Circle'] = _CIRCLE
DESCRIPTOR.message_types_by_name['Ellipse'] = _ELLIPSE
DESCRIPTOR.message_types_by_name['Quad'] = _QUAD
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['Frustum'] = _FRUSTUM
DESCRIPTOR.message_types_by_name['Cone'] = _CONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Line = _reflection.GeneratedProtocolMessageType('Line', (_message.Message,), dict(
  DESCRIPTOR = _LINE,
  __module__ = 'message.Geometry_pb2'
  # @@protoc_insertion_point(class_scope:message.Line)
  ))
_sym_db.RegisterMessage(Line)

Circle = _reflection.GeneratedProtocolMessageType('Circle', (_message.Message,), dict(
  DESCRIPTOR = _CIRCLE,
  __module__ = 'message.Geometry_pb2'
  # @@protoc_insertion_point(class_scope:message.Circle)
  ))
_sym_db.RegisterMessage(Circle)

Ellipse = _reflection.GeneratedProtocolMessageType('Ellipse', (_message.Message,), dict(
  DESCRIPTOR = _ELLIPSE,
  __module__ = 'message.Geometry_pb2'
  # @@protoc_insertion_point(class_scope:message.Ellipse)
  ))
_sym_db.RegisterMessage(Ellipse)

Quad = _reflection.GeneratedProtocolMessageType('Quad', (_message.Message,), dict(
  DESCRIPTOR = _QUAD,
  __module__ = 'message.Geometry_pb2'
  # @@protoc_insertion_point(class_scope:message.Quad)
  ))
_sym_db.RegisterMessage(Quad)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON,
  __module__ = 'message.Geometry_pb2'
  # @@protoc_insertion_point(class_scope:message.Polygon)
  ))
_sym_db.RegisterMessage(Polygon)

Frustum = _reflection.GeneratedProtocolMessageType('Frustum', (_message.Message,), dict(
  DESCRIPTOR = _FRUSTUM,
  __module__ = 'message.Geometry_pb2'
  # @@protoc_insertion_point(class_scope:message.Frustum)
  ))
_sym_db.RegisterMessage(Frustum)

Cone = _reflection.GeneratedProtocolMessageType('Cone', (_message.Message,), dict(
  DESCRIPTOR = _CONE,
  __module__ = 'message.Geometry_pb2'
  # @@protoc_insertion_point(class_scope:message.Cone)
  ))
_sym_db.RegisterMessage(Cone)


# @@protoc_insertion_point(module_scope)
