# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/nusight/DataPoint.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/nusight/DataPoint.proto',
  package='message.support.nusight',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'message/support/nusight/DataPoint.proto\x12\x17message.support.nusight\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n\tDataPoint\x12\r\n\x05label\x18\x01 \x01(\t\x12\x11\n\x05value\x18\x02 \x03(\x02\x42\x02\x10\x01\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_DATAPOINT = _descriptor.Descriptor(
  name='DataPoint',
  full_name='message.support.nusight.DataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='message.support.nusight.DataPoint.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='message.support.nusight.DataPoint.value', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.support.nusight.DataPoint.timestamp', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=193,
)

_DATAPOINT.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), dict(
  DESCRIPTOR = _DATAPOINT,
  __module__ = 'message.support.nusight.DataPoint_pb2'
  # @@protoc_insertion_point(class_scope:message.support.nusight.DataPoint)
  ))
_sym_db.RegisterMessage(DataPoint)


_DATAPOINT.fields_by_name['value']._options = None
# @@protoc_insertion_point(module_scope)
