# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/nusight/Overview.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from message.behaviour import Behaviour_pb2 as message_dot_behaviour_dot_Behaviour__pb2
from message.input import GameState_pb2 as message_dot_input_dot_GameState__pb2
import Vector_pb2 as Vector__pb2
import Matrix_pb2 as Matrix__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/nusight/Overview.proto',
  package='message.support.nusight',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&message/support/nusight/Overview.proto\x12\x17message.support.nusight\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!message/behaviour/Behaviour.proto\x1a\x1dmessage/input/GameState.proto\x1a\x0cVector.proto\x1a\x0cMatrix.proto\"\x80\x06\n\x08Overview\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08robot_id\x18\x02 \x01(\r\x12\x11\n\trole_name\x18\x03 \x01(\t\x12\x0f\n\x07\x62\x61ttery\x18\x04 \x01(\x02\x12\x0f\n\x07voltage\x18\x05 \x01(\x02\x12;\n\x0f\x62\x65haviour_state\x18\x06 \x01(\x0e\x32\".message.behaviour.Behaviour.State\x12\x1e\n\x0erobot_position\x18\x07 \x01(\x0b\x32\x06.fvec3\x12)\n\x19robot_position_covariance\x18\x08 \x01(\x0b\x32\x06.fmat3\x12\x1d\n\rball_position\x18\t \x01(\x0b\x32\x06.fvec2\x12(\n\x18\x62\x61ll_position_covariance\x18\n \x01(\x0b\x32\x06.fmat2\x12\x1b\n\x0bkick_target\x18\x0b \x01(\x0b\x32\x06.fvec2\x12\x35\n\tgame_mode\x18\x0c \x01(\x0e\x32\".message.input.GameState.Data.Mode\x12\x37\n\ngame_phase\x18\r \x01(\x0e\x32#.message.input.GameState.Data.Phase\x12\x43\n\x0epenalty_reason\x18\x0e \x01(\x0e\x32+.message.input.GameState.Data.PenaltyReason\x12\x35\n\x11last_camera_image\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0elast_seen_ball\x18\x10 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0elast_seen_goal\x18\x11 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1e\n\x0ewalk_path_plan\x18\x12 \x03(\x0b\x32\x06.fvec2\x12\x1c\n\x0cwalk_command\x18\x13 \x01(\x0b\x32\x06.fvec3b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,message_dot_behaviour_dot_Behaviour__pb2.DESCRIPTOR,message_dot_input_dot_GameState__pb2.DESCRIPTOR,Vector__pb2.DESCRIPTOR,Matrix__pb2.DESCRIPTOR,])




_OVERVIEW = _descriptor.Descriptor(
  name='Overview',
  full_name='message.support.nusight.Overview',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.support.nusight.Overview.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='message.support.nusight.Overview.robot_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role_name', full_name='message.support.nusight.Overview.role_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery', full_name='message.support.nusight.Overview.battery', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='message.support.nusight.Overview.voltage', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='behaviour_state', full_name='message.support.nusight.Overview.behaviour_state', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_position', full_name='message.support.nusight.Overview.robot_position', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_position_covariance', full_name='message.support.nusight.Overview.robot_position_covariance', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball_position', full_name='message.support.nusight.Overview.ball_position', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball_position_covariance', full_name='message.support.nusight.Overview.ball_position_covariance', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kick_target', full_name='message.support.nusight.Overview.kick_target', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_mode', full_name='message.support.nusight.Overview.game_mode', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_phase', full_name='message.support.nusight.Overview.game_phase', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='penalty_reason', full_name='message.support.nusight.Overview.penalty_reason', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_camera_image', full_name='message.support.nusight.Overview.last_camera_image', index=14,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_seen_ball', full_name='message.support.nusight.Overview.last_seen_ball', index=15,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_seen_goal', full_name='message.support.nusight.Overview.last_seen_goal', index=16,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='walk_path_plan', full_name='message.support.nusight.Overview.walk_path_plan', index=17,
      number=18, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='walk_command', full_name='message.support.nusight.Overview.walk_command', index=18,
      number=19, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=963,
)

_OVERVIEW.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OVERVIEW.fields_by_name['behaviour_state'].enum_type = message_dot_behaviour_dot_Behaviour__pb2._BEHAVIOUR_STATE
_OVERVIEW.fields_by_name['robot_position'].message_type = Vector__pb2._FVEC3
_OVERVIEW.fields_by_name['robot_position_covariance'].message_type = Matrix__pb2._FMAT3
_OVERVIEW.fields_by_name['ball_position'].message_type = Vector__pb2._FVEC2
_OVERVIEW.fields_by_name['ball_position_covariance'].message_type = Matrix__pb2._FMAT2
_OVERVIEW.fields_by_name['kick_target'].message_type = Vector__pb2._FVEC2
_OVERVIEW.fields_by_name['game_mode'].enum_type = message_dot_input_dot_GameState__pb2._GAMESTATE_DATA_MODE
_OVERVIEW.fields_by_name['game_phase'].enum_type = message_dot_input_dot_GameState__pb2._GAMESTATE_DATA_PHASE
_OVERVIEW.fields_by_name['penalty_reason'].enum_type = message_dot_input_dot_GameState__pb2._GAMESTATE_DATA_PENALTYREASON
_OVERVIEW.fields_by_name['last_camera_image'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OVERVIEW.fields_by_name['last_seen_ball'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OVERVIEW.fields_by_name['last_seen_goal'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OVERVIEW.fields_by_name['walk_path_plan'].message_type = Vector__pb2._FVEC2
_OVERVIEW.fields_by_name['walk_command'].message_type = Vector__pb2._FVEC3
DESCRIPTOR.message_types_by_name['Overview'] = _OVERVIEW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Overview = _reflection.GeneratedProtocolMessageType('Overview', (_message.Message,), dict(
  DESCRIPTOR = _OVERVIEW,
  __module__ = 'message.support.nusight.Overview_pb2'
  # @@protoc_insertion_point(class_scope:message.support.nusight.Overview)
  ))
_sym_db.RegisterMessage(Overview)


# @@protoc_insertion_point(module_scope)
