# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/platform/gazebo/Command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/platform/gazebo/Command.proto',
  package='message.platform.gazebo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%message/platform/gazebo/Command.proto\x12\x17message.platform.gazebo\"a\n\x07\x43ommand\x12\x33\n\x04type\x18\x01 \x01(\x0e\x32%.message.platform.gazebo.Command.Type\"!\n\x04Type\x12\t\n\x05RESET\x10\x00\x12\x0e\n\nRESET_TIME\x10\x01\x62\x06proto3')
)



_COMMAND_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='message.platform.gazebo.Command.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET_TIME', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=130,
  serialized_end=163,
)
_sym_db.RegisterEnumDescriptor(_COMMAND_TYPE)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='message.platform.gazebo.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='message.platform.gazebo.Command.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMAND_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=163,
)

_COMMAND.fields_by_name['type'].enum_type = _COMMAND_TYPE
_COMMAND_TYPE.containing_type = _COMMAND
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'message.platform.gazebo.Command_pb2'
  # @@protoc_insertion_point(class_scope:message.platform.gazebo.Command)
  ))
_sym_db.RegisterMessage(Command)


# @@protoc_insertion_point(module_scope)
