# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/platform/gazebo/RawSensors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from message.platform.darwin import DarwinSensors_pb2 as message_dot_platform_dot_darwin_dot_DarwinSensors__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/platform/gazebo/RawSensors.proto',
  package='message.platform.gazebo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(message/platform/gazebo/RawSensors.proto\x12\x17message.platform.gazebo\x1a+message/platform/darwin/DarwinSensors.proto\"T\n\nRawSensors\x12\r\n\x05model\x18\x01 \x01(\t\x12\x37\n\x07sensors\x18\x02 \x01(\x0b\x32&.message.platform.darwin.DarwinSensorsb\x06proto3')
  ,
  dependencies=[message_dot_platform_dot_darwin_dot_DarwinSensors__pb2.DESCRIPTOR,])




_RAWSENSORS = _descriptor.Descriptor(
  name='RawSensors',
  full_name='message.platform.gazebo.RawSensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='message.platform.gazebo.RawSensors.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensors', full_name='message.platform.gazebo.RawSensors.sensors', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=198,
)

_RAWSENSORS.fields_by_name['sensors'].message_type = message_dot_platform_dot_darwin_dot_DarwinSensors__pb2._DARWINSENSORS
DESCRIPTOR.message_types_by_name['RawSensors'] = _RAWSENSORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RawSensors = _reflection.GeneratedProtocolMessageType('RawSensors', (_message.Message,), dict(
  DESCRIPTOR = _RAWSENSORS,
  __module__ = 'message.platform.gazebo.RawSensors_pb2'
  # @@protoc_insertion_point(class_scope:message.platform.gazebo.RawSensors)
  ))
_sym_db.RegisterMessage(RawSensors)


# @@protoc_insertion_point(module_scope)
