# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/platform/gazebo/Simulation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/platform/gazebo/Simulation.proto',
  package='message.platform.gazebo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(message/platform/gazebo/Simulation.proto\x12\x17message.platform.gazebo\"8\n\nSimulation\x12\x17\n\x0fsimulation_time\x18\x01 \x01(\x01\x12\x11\n\treal_time\x18\x02 \x01(\x01\x62\x06proto3')
)




_SIMULATION = _descriptor.Descriptor(
  name='Simulation',
  full_name='message.platform.gazebo.Simulation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='simulation_time', full_name='message.platform.gazebo.Simulation.simulation_time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='real_time', full_name='message.platform.gazebo.Simulation.real_time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['Simulation'] = _SIMULATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Simulation = _reflection.GeneratedProtocolMessageType('Simulation', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATION,
  __module__ = 'message.platform.gazebo.Simulation_pb2'
  # @@protoc_insertion_point(class_scope:message.platform.gazebo.Simulation)
  ))
_sym_db.RegisterMessage(Simulation)


# @@protoc_insertion_point(module_scope)
