# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/platform/gazebo/Torso.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Matrix_pb2 as Matrix__pb2
import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/platform/gazebo/Torso.proto',
  package='message.platform.gazebo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#message/platform/gazebo/Torso.proto\x12\x17message.platform.gazebo\x1a\x0cMatrix.proto\x1a\x0cVector.proto\"\x82\x01\n\x05Torso\x12\r\n\x05model\x18\x01 \x01(\t\x12\x12\n\x03Htw\x18\x02 \x01(\x0b\x32\x05.mat4\x12\x16\n\x07omegaTw\x18\x03 \x01(\x0b\x32\x05.vec3\x12\x16\n\x07\x61lphaTw\x18\x04 \x01(\x0b\x32\x05.vec3\x12\x12\n\x03vTw\x18\x05 \x01(\x0b\x32\x05.vec3\x12\x12\n\x03\x61Tw\x18\x06 \x01(\x0b\x32\x05.vec3b\x06proto3')
  ,
  dependencies=[Matrix__pb2.DESCRIPTOR,Vector__pb2.DESCRIPTOR,])




_TORSO = _descriptor.Descriptor(
  name='Torso',
  full_name='message.platform.gazebo.Torso',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='message.platform.gazebo.Torso.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Htw', full_name='message.platform.gazebo.Torso.Htw', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='omegaTw', full_name='message.platform.gazebo.Torso.omegaTw', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alphaTw', full_name='message.platform.gazebo.Torso.alphaTw', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vTw', full_name='message.platform.gazebo.Torso.vTw', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aTw', full_name='message.platform.gazebo.Torso.aTw', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=223,
)

_TORSO.fields_by_name['Htw'].message_type = Matrix__pb2._MAT4
_TORSO.fields_by_name['omegaTw'].message_type = Vector__pb2._VEC3
_TORSO.fields_by_name['alphaTw'].message_type = Vector__pb2._VEC3
_TORSO.fields_by_name['vTw'].message_type = Vector__pb2._VEC3
_TORSO.fields_by_name['aTw'].message_type = Vector__pb2._VEC3
DESCRIPTOR.message_types_by_name['Torso'] = _TORSO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Torso = _reflection.GeneratedProtocolMessageType('Torso', (_message.Message,), dict(
  DESCRIPTOR = _TORSO,
  __module__ = 'message.platform.gazebo.Torso_pb2'
  # @@protoc_insertion_point(class_scope:message.platform.gazebo.Torso)
  ))
_sym_db.RegisterMessage(Torso)


# @@protoc_insertion_point(module_scope)
