# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/FieldDescription.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/FieldDescription.proto',
  package='message.support',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&message/support/FieldDescription.proto\x12\x0fmessage.support\x1a\x0cVector.proto\"\xd8\x06\n\x10\x46ieldDescription\x12\x13\n\x0b\x62\x61ll_radius\x18\x01 \x01(\x01\x12\x1b\n\x13goalpost_top_height\x18\x02 \x01(\x01\x12\x1b\n\x13penalty_robot_start\x18\x03 \x01(\x01\x12\x1d\n\x0egoalpost_own_l\x18\x04 \x01(\x0b\x32\x05.vec2\x12\x1d\n\x0egoalpost_own_r\x18\x05 \x01(\x0b\x32\x05.vec2\x12\x1d\n\x0egoalpost_opp_l\x18\x06 \x01(\x0b\x32\x05.vec2\x12\x1d\n\x0egoalpost_opp_r\x18\x07 \x01(\x0b\x32\x05.vec2\x12\x45\n\ndimensions\x18\x08 \x01(\x0b\x32\x31.message.support.FieldDescription.FieldDimensions\x1a\x86\x04\n\x0f\x46ieldDimensions\x12\x12\n\nline_width\x18\x01 \x01(\x01\x12\x12\n\nmark_width\x18\x02 \x01(\x01\x12\x14\n\x0c\x66ield_length\x18\x03 \x01(\x01\x12\x13\n\x0b\x66ield_width\x18\x04 \x01(\x01\x12\x45\n\rgoalpost_type\x18\x05 \x01(\x0e\x32..message.support.FieldDescription.GoalpostType\x12\x12\n\ngoal_depth\x18\x06 \x01(\x01\x12\x12\n\ngoal_width\x18\x07 \x01(\x01\x12\x18\n\x10goal_area_length\x18\x08 \x01(\x01\x12\x17\n\x0fgoal_area_width\x18\t \x01(\x01\x12\x1c\n\x14goal_crossbar_height\x18\n \x01(\x01\x12\x16\n\x0egoalpost_width\x18\x0b \x01(\x01\x12\x16\n\x0egoalpost_depth\x18\x0c \x01(\x01\x12\x1b\n\x13goal_crossbar_width\x18\r \x01(\x01\x12\x1b\n\x13goal_crossbar_depth\x18\x0e \x01(\x01\x12\x17\n\x0fgoal_net_height\x18\x0f \x01(\x01\x12\x1d\n\x15penalty_mark_distance\x18\x10 \x01(\x01\x12\x1e\n\x16\x63\x65nter_circle_diameter\x18\x11 \x01(\x01\x12\x1e\n\x16\x62order_strip_min_width\x18\x12 \x01(\x01\")\n\x0cGoalpostType\x12\r\n\tRECTANGLE\x10\x00\x12\n\n\x06\x43IRCLE\x10\x01\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])



_FIELDDESCRIPTION_GOALPOSTTYPE = _descriptor.EnumDescriptor(
  name='GoalpostType',
  full_name='message.support.FieldDescription.GoalpostType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RECTANGLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CIRCLE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=889,
  serialized_end=930,
)
_sym_db.RegisterEnumDescriptor(_FIELDDESCRIPTION_GOALPOSTTYPE)


_FIELDDESCRIPTION_FIELDDIMENSIONS = _descriptor.Descriptor(
  name='FieldDimensions',
  full_name='message.support.FieldDescription.FieldDimensions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line_width', full_name='message.support.FieldDescription.FieldDimensions.line_width', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mark_width', full_name='message.support.FieldDescription.FieldDimensions.mark_width', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_length', full_name='message.support.FieldDescription.FieldDimensions.field_length', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_width', full_name='message.support.FieldDescription.FieldDimensions.field_width', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goalpost_type', full_name='message.support.FieldDescription.FieldDimensions.goalpost_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goal_depth', full_name='message.support.FieldDescription.FieldDimensions.goal_depth', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goal_width', full_name='message.support.FieldDescription.FieldDimensions.goal_width', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goal_area_length', full_name='message.support.FieldDescription.FieldDimensions.goal_area_length', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goal_area_width', full_name='message.support.FieldDescription.FieldDimensions.goal_area_width', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goal_crossbar_height', full_name='message.support.FieldDescription.FieldDimensions.goal_crossbar_height', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goalpost_width', full_name='message.support.FieldDescription.FieldDimensions.goalpost_width', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goalpost_depth', full_name='message.support.FieldDescription.FieldDimensions.goalpost_depth', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goal_crossbar_width', full_name='message.support.FieldDescription.FieldDimensions.goal_crossbar_width', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goal_crossbar_depth', full_name='message.support.FieldDescription.FieldDimensions.goal_crossbar_depth', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goal_net_height', full_name='message.support.FieldDescription.FieldDimensions.goal_net_height', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='penalty_mark_distance', full_name='message.support.FieldDescription.FieldDimensions.penalty_mark_distance', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='center_circle_diameter', full_name='message.support.FieldDescription.FieldDimensions.center_circle_diameter', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='border_strip_min_width', full_name='message.support.FieldDescription.FieldDimensions.border_strip_min_width', index=17,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=887,
)

_FIELDDESCRIPTION = _descriptor.Descriptor(
  name='FieldDescription',
  full_name='message.support.FieldDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ball_radius', full_name='message.support.FieldDescription.ball_radius', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goalpost_top_height', full_name='message.support.FieldDescription.goalpost_top_height', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='penalty_robot_start', full_name='message.support.FieldDescription.penalty_robot_start', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goalpost_own_l', full_name='message.support.FieldDescription.goalpost_own_l', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goalpost_own_r', full_name='message.support.FieldDescription.goalpost_own_r', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goalpost_opp_l', full_name='message.support.FieldDescription.goalpost_opp_l', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goalpost_opp_r', full_name='message.support.FieldDescription.goalpost_opp_r', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='message.support.FieldDescription.dimensions', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FIELDDESCRIPTION_FIELDDIMENSIONS, ],
  enum_types=[
    _FIELDDESCRIPTION_GOALPOSTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=930,
)

_FIELDDESCRIPTION_FIELDDIMENSIONS.fields_by_name['goalpost_type'].enum_type = _FIELDDESCRIPTION_GOALPOSTTYPE
_FIELDDESCRIPTION_FIELDDIMENSIONS.containing_type = _FIELDDESCRIPTION
_FIELDDESCRIPTION.fields_by_name['goalpost_own_l'].message_type = Vector__pb2._VEC2
_FIELDDESCRIPTION.fields_by_name['goalpost_own_r'].message_type = Vector__pb2._VEC2
_FIELDDESCRIPTION.fields_by_name['goalpost_opp_l'].message_type = Vector__pb2._VEC2
_FIELDDESCRIPTION.fields_by_name['goalpost_opp_r'].message_type = Vector__pb2._VEC2
_FIELDDESCRIPTION.fields_by_name['dimensions'].message_type = _FIELDDESCRIPTION_FIELDDIMENSIONS
_FIELDDESCRIPTION_GOALPOSTTYPE.containing_type = _FIELDDESCRIPTION
DESCRIPTOR.message_types_by_name['FieldDescription'] = _FIELDDESCRIPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FieldDescription = _reflection.GeneratedProtocolMessageType('FieldDescription', (_message.Message,), dict(

  FieldDimensions = _reflection.GeneratedProtocolMessageType('FieldDimensions', (_message.Message,), dict(
    DESCRIPTOR = _FIELDDESCRIPTION_FIELDDIMENSIONS,
    __module__ = 'message.support.FieldDescription_pb2'
    # @@protoc_insertion_point(class_scope:message.support.FieldDescription.FieldDimensions)
    ))
  ,
  DESCRIPTOR = _FIELDDESCRIPTION,
  __module__ = 'message.support.FieldDescription_pb2'
  # @@protoc_insertion_point(class_scope:message.support.FieldDescription)
  ))
_sym_db.RegisterMessage(FieldDescription)
_sym_db.RegisterMessage(FieldDescription.FieldDimensions)


# @@protoc_insertion_point(module_scope)
