# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/GlobalConfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/GlobalConfig.proto',
  package='message.support',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"message/support/GlobalConfig.proto\x12\x0fmessage.support\"0\n\x0cGlobalConfig\x12\x10\n\x08playerId\x18\x01 \x01(\r\x12\x0e\n\x06teamId\x18\x02 \x01(\rb\x06proto3')
)




_GLOBALCONFIG = _descriptor.Descriptor(
  name='GlobalConfig',
  full_name='message.support.GlobalConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerId', full_name='message.support.GlobalConfig.playerId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teamId', full_name='message.support.GlobalConfig.teamId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['GlobalConfig'] = _GLOBALCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GlobalConfig = _reflection.GeneratedProtocolMessageType('GlobalConfig', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALCONFIG,
  __module__ = 'message.support.GlobalConfig_pb2'
  # @@protoc_insertion_point(class_scope:message.support.GlobalConfig)
  ))
_sym_db.RegisterMessage(GlobalConfig)


# @@protoc_insertion_point(module_scope)
