# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/SaveConfiguration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/SaveConfiguration.proto',
  package='message.support',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'message/support/SaveConfiguration.proto\x12\x0fmessage.support\"1\n\x11SaveConfiguration\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\tb\x06proto3')
)




_SAVECONFIGURATION = _descriptor.Descriptor(
  name='SaveConfiguration',
  full_name='message.support.SaveConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='message.support.SaveConfiguration.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='message.support.SaveConfiguration.config', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['SaveConfiguration'] = _SAVECONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SaveConfiguration = _reflection.GeneratedProtocolMessageType('SaveConfiguration', (_message.Message,), dict(
  DESCRIPTOR = _SAVECONFIGURATION,
  __module__ = 'message.support.SaveConfiguration_pb2'
  # @@protoc_insertion_point(class_scope:message.support.SaveConfiguration)
  ))
_sym_db.RegisterMessage(SaveConfiguration)


# @@protoc_insertion_point(module_scope)
