# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/motion/FootTarget.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Matrix_pb2 as Matrix__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/motion/FootTarget.proto',
  package='message.motion',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fmessage/motion/FootTarget.proto\x12\x0emessage.motion\x1a\x0cMatrix.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n\nFootTarget\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10isRightFootSwing\x18\x02 \x01(\x08\x12\x14\n\x05Haf_s\x18\x03 \x01(\x0b\x32\x05.mat4b\x06proto3')
  ,
  dependencies=[Matrix__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_FOOTTARGET = _descriptor.Descriptor(
  name='FootTarget',
  full_name='message.motion.FootTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.motion.FootTarget.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isRightFootSwing', full_name='message.motion.FootTarget.isRightFootSwing', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Haf_s', full_name='message.motion.FootTarget.Haf_s', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=205,
)

_FOOTTARGET.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_FOOTTARGET.fields_by_name['Haf_s'].message_type = Matrix__pb2._MAT4
DESCRIPTOR.message_types_by_name['FootTarget'] = _FOOTTARGET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FootTarget = _reflection.GeneratedProtocolMessageType('FootTarget', (_message.Message,), dict(
  DESCRIPTOR = _FOOTTARGET,
  __module__ = 'message.motion.FootTarget_pb2'
  # @@protoc_insertion_point(class_scope:message.motion.FootTarget)
  ))
_sym_db.RegisterMessage(FootTarget)


# @@protoc_insertion_point(module_scope)
