# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/motion/HeadCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/motion/HeadCommand.proto',
  package='message.motion',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n message/motion/HeadCommand.proto\x12\x0emessage.motion\"=\n\x0bHeadCommand\x12\x0b\n\x03yaw\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x12\n\nrobotSpace\x18\x03 \x01(\x08\"\x12\n\x10HeadMotionUpdateb\x06proto3')
)




_HEADCOMMAND = _descriptor.Descriptor(
  name='HeadCommand',
  full_name='message.motion.HeadCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='yaw', full_name='message.motion.HeadCommand.yaw', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='message.motion.HeadCommand.pitch', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robotSpace', full_name='message.motion.HeadCommand.robotSpace', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=113,
)


_HEADMOTIONUPDATE = _descriptor.Descriptor(
  name='HeadMotionUpdate',
  full_name='message.motion.HeadMotionUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['HeadCommand'] = _HEADCOMMAND
DESCRIPTOR.message_types_by_name['HeadMotionUpdate'] = _HEADMOTIONUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeadCommand = _reflection.GeneratedProtocolMessageType('HeadCommand', (_message.Message,), dict(
  DESCRIPTOR = _HEADCOMMAND,
  __module__ = 'message.motion.HeadCommand_pb2'
  # @@protoc_insertion_point(class_scope:message.motion.HeadCommand)
  ))
_sym_db.RegisterMessage(HeadCommand)

HeadMotionUpdate = _reflection.GeneratedProtocolMessageType('HeadMotionUpdate', (_message.Message,), dict(
  DESCRIPTOR = _HEADMOTIONUPDATE,
  __module__ = 'message.motion.HeadCommand_pb2'
  # @@protoc_insertion_point(class_scope:message.motion.HeadMotionUpdate)
  ))
_sym_db.RegisterMessage(HeadMotionUpdate)


# @@protoc_insertion_point(module_scope)
