# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/motion/KickCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/motion/KickCommand.proto',
  package='message.motion',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n message/motion/KickCommand.proto\x12\x0emessage.motion\x1a\x0cVector.proto\"x\n\x0bKickCommand\x12\x15\n\x06target\x18\x01 \x01(\x0b\x32\x05.vec3\x12\x18\n\tdirection\x18\x02 \x01(\x0b\x32\x05.vec3\x12\x38\n\x0fkickCommandType\x18\x03 \x01(\x0e\x32\x1f.message.motion.KickCommandType\":\n\x11KickScriptCommand\x12\x18\n\tdirection\x18\x01 \x01(\x0b\x32\x05.vec3\x12\x0b\n\x03leg\x18\x02 \x01(\r\"\x8d\x01\n\x11KickPlannerConfig\x12\x19\n\x11max_ball_distance\x18\x01 \x01(\x02\x12\x1b\n\x13kick_corridor_width\x18\x02 \x01(\x02\x12\x1e\n\x16seconds_not_seen_limit\x18\x03 \x01(\x02\x12 \n\x18kick_forward_angle_limit\x18\x04 \x01(\x02\"\x0e\n\x0cKickFinished\"$\n\x0cIKKickParams\x12\x14\n\x0cstand_height\x18\x01 \x01(\x02*(\n\x0fKickCommandType\x12\n\n\x06NORMAL\x10\x00\x12\t\n\x05POWER\x10\x01\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])

_KICKCOMMANDTYPE = _descriptor.EnumDescriptor(
  name='KickCommandType',
  full_name='message.motion.KickCommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POWER', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=446,
  serialized_end=486,
)
_sym_db.RegisterEnumDescriptor(_KICKCOMMANDTYPE)

KickCommandType = enum_type_wrapper.EnumTypeWrapper(_KICKCOMMANDTYPE)
NORMAL = 0
POWER = 1



_KICKCOMMAND = _descriptor.Descriptor(
  name='KickCommand',
  full_name='message.motion.KickCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='message.motion.KickCommand.target', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='message.motion.KickCommand.direction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kickCommandType', full_name='message.motion.KickCommand.kickCommandType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=186,
)


_KICKSCRIPTCOMMAND = _descriptor.Descriptor(
  name='KickScriptCommand',
  full_name='message.motion.KickScriptCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='message.motion.KickScriptCommand.direction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leg', full_name='message.motion.KickScriptCommand.leg', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=246,
)


_KICKPLANNERCONFIG = _descriptor.Descriptor(
  name='KickPlannerConfig',
  full_name='message.motion.KickPlannerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_ball_distance', full_name='message.motion.KickPlannerConfig.max_ball_distance', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kick_corridor_width', full_name='message.motion.KickPlannerConfig.kick_corridor_width', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seconds_not_seen_limit', full_name='message.motion.KickPlannerConfig.seconds_not_seen_limit', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kick_forward_angle_limit', full_name='message.motion.KickPlannerConfig.kick_forward_angle_limit', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=390,
)


_KICKFINISHED = _descriptor.Descriptor(
  name='KickFinished',
  full_name='message.motion.KickFinished',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=406,
)


_IKKICKPARAMS = _descriptor.Descriptor(
  name='IKKickParams',
  full_name='message.motion.IKKickParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stand_height', full_name='message.motion.IKKickParams.stand_height', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=444,
)

_KICKCOMMAND.fields_by_name['target'].message_type = Vector__pb2._VEC3
_KICKCOMMAND.fields_by_name['direction'].message_type = Vector__pb2._VEC3
_KICKCOMMAND.fields_by_name['kickCommandType'].enum_type = _KICKCOMMANDTYPE
_KICKSCRIPTCOMMAND.fields_by_name['direction'].message_type = Vector__pb2._VEC3
DESCRIPTOR.message_types_by_name['KickCommand'] = _KICKCOMMAND
DESCRIPTOR.message_types_by_name['KickScriptCommand'] = _KICKSCRIPTCOMMAND
DESCRIPTOR.message_types_by_name['KickPlannerConfig'] = _KICKPLANNERCONFIG
DESCRIPTOR.message_types_by_name['KickFinished'] = _KICKFINISHED
DESCRIPTOR.message_types_by_name['IKKickParams'] = _IKKICKPARAMS
DESCRIPTOR.enum_types_by_name['KickCommandType'] = _KICKCOMMANDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KickCommand = _reflection.GeneratedProtocolMessageType('KickCommand', (_message.Message,), dict(
  DESCRIPTOR = _KICKCOMMAND,
  __module__ = 'message.motion.KickCommand_pb2'
  # @@protoc_insertion_point(class_scope:message.motion.KickCommand)
  ))
_sym_db.RegisterMessage(KickCommand)

KickScriptCommand = _reflection.GeneratedProtocolMessageType('KickScriptCommand', (_message.Message,), dict(
  DESCRIPTOR = _KICKSCRIPTCOMMAND,
  __module__ = 'message.motion.KickCommand_pb2'
  # @@protoc_insertion_point(class_scope:message.motion.KickScriptCommand)
  ))
_sym_db.RegisterMessage(KickScriptCommand)

KickPlannerConfig = _reflection.GeneratedProtocolMessageType('KickPlannerConfig', (_message.Message,), dict(
  DESCRIPTOR = _KICKPLANNERCONFIG,
  __module__ = 'message.motion.KickCommand_pb2'
  # @@protoc_insertion_point(class_scope:message.motion.KickPlannerConfig)
  ))
_sym_db.RegisterMessage(KickPlannerConfig)

KickFinished = _reflection.GeneratedProtocolMessageType('KickFinished', (_message.Message,), dict(
  DESCRIPTOR = _KICKFINISHED,
  __module__ = 'message.motion.KickCommand_pb2'
  # @@protoc_insertion_point(class_scope:message.motion.KickFinished)
  ))
_sym_db.RegisterMessage(KickFinished)

IKKickParams = _reflection.GeneratedProtocolMessageType('IKKickParams', (_message.Message,), dict(
  DESCRIPTOR = _IKKICKPARAMS,
  __module__ = 'message.motion.KickCommand_pb2'
  # @@protoc_insertion_point(class_scope:message.motion.IKKickParams)
  ))
_sym_db.RegisterMessage(IKKickParams)


# @@protoc_insertion_point(module_scope)
