# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/output/CompressedImage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import Matrix_pb2 as Matrix__pb2
import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/output/CompressedImage.proto',
  package='message.output',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$message/output/CompressedImage.proto\x12\x0emessage.output\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cMatrix.proto\x1a\x0cVector.proto\"\xc0\x03\n\x0f\x43ompressedImage\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\r\x12\x1a\n\ndimensions\x18\x02 \x01(\x0b\x32\x06.uvec2\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x11\n\tcamera_id\x18\x04 \x01(\r\x12\x0c\n\x04name\x18\x05 \x01(\t\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\x03Hcw\x18\x07 \x01(\x0b\x32\x05.mat4\x12\x32\n\x04lens\x18\x08 \x01(\x0b\x32$.message.output.CompressedImage.Lens\x1a\xda\x01\n\x04Lens\x12\x43\n\nprojection\x18\x01 \x01(\x0e\x32/.message.output.CompressedImage.Lens.Projection\x12\x14\n\x0c\x66ocal_length\x18\x02 \x01(\x02\x12\x13\n\x03\x66ov\x18\x03 \x01(\x0b\x32\x06.fvec2\x12\x16\n\x06\x63\x65ntre\x18\x04 \x01(\x0b\x32\x06.fvec2\"J\n\nProjection\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bRECTILINEAR\x10\x01\x12\x0f\n\x0b\x45QUIDISTANT\x10\x02\x12\r\n\tEQUISOLID\x10\x03\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,Matrix__pb2.DESCRIPTOR,Vector__pb2.DESCRIPTOR,])



_COMPRESSEDIMAGE_LENS_PROJECTION = _descriptor.EnumDescriptor(
  name='Projection',
  full_name='message.output.CompressedImage.Lens.Projection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECTILINEAR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EQUIDISTANT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EQUISOLID', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=492,
  serialized_end=566,
)
_sym_db.RegisterEnumDescriptor(_COMPRESSEDIMAGE_LENS_PROJECTION)


_COMPRESSEDIMAGE_LENS = _descriptor.Descriptor(
  name='Lens',
  full_name='message.output.CompressedImage.Lens',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='projection', full_name='message.output.CompressedImage.Lens.projection', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='focal_length', full_name='message.output.CompressedImage.Lens.focal_length', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fov', full_name='message.output.CompressedImage.Lens.fov', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='centre', full_name='message.output.CompressedImage.Lens.centre', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPRESSEDIMAGE_LENS_PROJECTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=566,
)

_COMPRESSEDIMAGE = _descriptor.Descriptor(
  name='CompressedImage',
  full_name='message.output.CompressedImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='format', full_name='message.output.CompressedImage.format', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='message.output.CompressedImage.dimensions', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='message.output.CompressedImage.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='message.output.CompressedImage.camera_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='message.output.CompressedImage.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.output.CompressedImage.timestamp', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Hcw', full_name='message.output.CompressedImage.Hcw', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lens', full_name='message.output.CompressedImage.lens', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COMPRESSEDIMAGE_LENS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=566,
)

_COMPRESSEDIMAGE_LENS.fields_by_name['projection'].enum_type = _COMPRESSEDIMAGE_LENS_PROJECTION
_COMPRESSEDIMAGE_LENS.fields_by_name['fov'].message_type = Vector__pb2._FVEC2
_COMPRESSEDIMAGE_LENS.fields_by_name['centre'].message_type = Vector__pb2._FVEC2
_COMPRESSEDIMAGE_LENS.containing_type = _COMPRESSEDIMAGE
_COMPRESSEDIMAGE_LENS_PROJECTION.containing_type = _COMPRESSEDIMAGE_LENS
_COMPRESSEDIMAGE.fields_by_name['dimensions'].message_type = Vector__pb2._UVEC2
_COMPRESSEDIMAGE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_COMPRESSEDIMAGE.fields_by_name['Hcw'].message_type = Matrix__pb2._MAT4
_COMPRESSEDIMAGE.fields_by_name['lens'].message_type = _COMPRESSEDIMAGE_LENS
DESCRIPTOR.message_types_by_name['CompressedImage'] = _COMPRESSEDIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompressedImage = _reflection.GeneratedProtocolMessageType('CompressedImage', (_message.Message,), dict(

  Lens = _reflection.GeneratedProtocolMessageType('Lens', (_message.Message,), dict(
    DESCRIPTOR = _COMPRESSEDIMAGE_LENS,
    __module__ = 'message.output.CompressedImage_pb2'
    # @@protoc_insertion_point(class_scope:message.output.CompressedImage.Lens)
    ))
  ,
  DESCRIPTOR = _COMPRESSEDIMAGE,
  __module__ = 'message.output.CompressedImage_pb2'
  # @@protoc_insertion_point(class_scope:message.output.CompressedImage)
  ))
_sym_db.RegisterMessage(CompressedImage)
_sym_db.RegisterMessage(CompressedImage.Lens)


# @@protoc_insertion_point(module_scope)
